<?php
use think\Env;

return [
    // 环境变量
    'app_debug'     => Env::get('app_debug'),
    'app_trace'     => Env::get('app_trace'),
    'app_test'      => Env::get('app_test'),
    'app_status'    => Env::get('app_status'),
    'default_module'    => Env::get('app_module'),

    'default_return_type'   => 'html',
    'default_timezone'  => 'Asia/Shanghai',
    'controller_suffix' => true,
    'url_convert'       => false,

    //APP 下载
    'app_download_ios' =>  'http://itunes.apple.com/cn/app/id1190844492?mt=8',
    'app_download_apk' =>  'http://android.myapp.com/myapp/detail.htm?apkName=com.juxian.bosscomments',
    'app_download_wechat' =>  'http://a.app.qq.com/o/simple.jsp?pkgname=com.juxian.bosscomments',
    'app_download_apk_mobile' =>  'http://a.app.qq.com/o/simple.jsp?pkgname=com.juxian.bosscomments',

    // 错误处理
    'show_error_msg'    => true,
    'exception_handle'  => '',
    'http_exception_template'    =>  [
        401 => APP_PATH.'html/401.html',
        404 => APP_PATH.'html/404.html',
        500 => APP_PATH.'html/50x.html',
        502 => APP_PATH.'html/50x.html',
        503 => APP_PATH.'html/50x.html',
        504 => APP_PATH.'html/50x.html',
    ],
    
    'log'               => [
        'type'      => 'file', 
        'apart_level'   => ['error','sql'],
    ],
    
     'cache'             =>[
         'type'  => 'Memcache',
         'host'  => '192.168.0.9',
         'port'  => '11211',
     ],

    'dictionary_expires'         => 12,  //字典客户端缓存时间，单位:秒
    'third:linked-cache-prefix' => "_PHP_",


    //数据库货币单位：分; 1元 = 100分
    'db_currency_unit'  => 100,
    'db_workplace'      => [
        'database'  => 'bc_workplace', 'type'  => 'mysql',
        'hostname'  => Env::get('mysql.hostname'), 'hostport' =>Env::get('mysql.hostport'),
        'username'  => Env::get('mysql.username'), 'password' => Env::get('mysql.password'),
        'debug'     => Env::get('app_debug'),
        'params'    => [ \PDO::ATTR_PERSISTENT => true,],
        'charset'   => 'utf8',
        'prefix'    => '',
        'deploy'    => 0,
        'rw_separate'   => false,
        'master_num'    => 1,
        'slave_no'      => '',
        'fields_strict' => true,
        'resultset_type'=> 'array',
        'auto_timestamp'=> true,
        'sql_explain'   => false,
    ],
    'db_passports'      => [
        'database'  => 'bc_passports', 'type'  => 'mysql',
        'hostname'  => Env::get('mysql.hostname'), 'hostport' =>Env::get('mysql.hostport'),
        'username'  => Env::get('mysql.username'), 'password' => Env::get('mysql.password'),
        'debug'     => Env::get('app_debug'),
        'params'    => [ \PDO::ATTR_PERSISTENT => true,],
        'charset'   => 'utf8',
        'prefix'    => '',
        'deploy'    => 0,
        'rw_separate'   => false,
        'master_num'    => 1,
        'slave_no'      => '',
        'fields_strict' => true,
        'resultset_type'=> 'array',
        'auto_timestamp'=> true,
    ],
    'db_tradesystem'      => [
        'database'  => 'bc_tradesystem', 'type'  => 'mysql',
        'hostname'  => Env::get('mysql.hostname'), 'hostport' =>Env::get('mysql.hostport'),
        'username'  => Env::get('mysql.username'), 'password' => Env::get('mysql.password'),
        'debug'     => Env::get('app_debug'),
        'params'    => [ \PDO::ATTR_PERSISTENT => true,],
        'charset'   => 'utf8',
        'prefix'    => '',
        'deploy'    => 0,
        'rw_separate'   => false,
        'master_num'    => 1,
        'slave_no'      => '',
        'fields_strict' => true,
        'resultset_type'=> 'array',
        'auto_timestamp'=> true,
        'sql_explain'   => false,
    ],
    'db_admin'      => [
        'database'  => 'bc_admin', 'type'  => 'mysql',
        'hostname'  => Env::get('mysql.hostname'), 'hostport' =>Env::get('mysql.hostport'),
        'username'  => Env::get('mysql.username'), 'password' => Env::get('mysql.password'),
        'debug'     => Env::get('app_debug'),
        'params'    => [ \PDO::ATTR_PERSISTENT => true,],
        'charset'   => 'utf8',
        'prefix'    => '',
        'deploy'    => 0,
        'rw_separate'   => false,
        'master_num'    => 1,
        'slave_no'      => '',
        'fields_strict' => true,
        'resultset_type'=> 'array',
        'auto_timestamp'=> true,
        'sql_explain'   => false,
    ],
    'db_io'      => [
        'database'  => '__bc_io', 'type'  => 'mysql',
        'hostname'  => Env::get('mysql.hostname'), 'hostport' =>Env::get('mysql.hostport'),
        'username'  => Env::get('mysql.username'), 'password' => Env::get('mysql.password'),
        'debug'     => Env::get('app_debug'),
        'params'    => [ \PDO::ATTR_PERSISTENT => true,],
        'charset'   => 'utf8',
        'prefix'    => '',
        'deploy'    => 0,
        'rw_separate'   => false,
        'master_num'    => 1,
        'slave_no'      => '',
        'fields_strict' => true,
        'resultset_type'=> 'array',
        'auto_timestamp'=> true,
        'sql_explain'   => false,
    ],
    'db_opinion'      => [
        'database'  => 'bc_opinion', 'type'  => 'mysql',
        'hostname'  => Env::get('mysql.hostname'), 'hostport' =>Env::get('mysql.hostport'),
        'username'  => Env::get('mysql.username'), 'password' => Env::get('mysql.password'),
        'debug'     => Env::get('app_debug'),
        'params'    => [ \PDO::ATTR_PERSISTENT => true,],
        'charset'   => 'utf8',
        'prefix'    => '',
        'deploy'    => 0,
        'rw_separate'   => false,
        'master_num'    => 1,
        'slave_no'      => '',
        'fields_strict' => true,
        'resultset_type'=> 'array',
        'auto_timestamp'=> true,
        'sql_explain'   => false,
    ],
];

